name: Nightly native Mac build

on:
  schedule:
    - cron:  '1 15 * * *'

jobs:
  build-mac-native:

    runs-on: macos-latest
    
    steps:
    - uses: actions/checkout@master
      name: checkout
      
    - run: ./bintray_nightly_check.sh
      name: nightly-check
      env:
        BINTRAY_USER: ${{ secrets.BINTRAY_USER }}
        BINTRAY_API_KEY: ${{ secrets.BINTRAY_API_KEY }}
      
    - name: Install Qt
      uses: jurplel/install-qt-action@v2
      
    - run: ./build_macos_native.sh
      name: build-for-mac
    
    - run: ./bintray_nightly_upload.sh ./build/bin/mac.zip mac
      name: upload-bintray-mac-build
      env:
        BINTRAY_USER: ${{ secrets.BINTRAY_USER }}
        BINTRAY_API_KEY: ${{ secrets.BINTRAY_API_KEY }}
